/*
    @file main.cpp
    @brief This is a simple JSON parser written in C++ that prints out the data entries
    from dataEntries.json

    Author: Zhonghe Cai
    Version: 1.0

    DO NOT EDIT THIS FILE. 
    If you want to add your own data entry, edit the dataEntries.json file instead.
*/

#include <filesystem>
#include <fstream>
#include <iostream>
#include "nlohmann/json.hpp"
#include <string>

using json = nlohmann::json;

int main() {
    std::filesystem::path data_path = std::filesystem::path(__FILE__).parent_path().parent_path() / "dataEntries.json";
    std::ifstream input(data_path);
    if (!input) {
        std::cerr << "Could not open " << data_path << "\n";
        return 1;
    }

    try {
        json data = json::parse(input);

        if (!data.is_array()) {
            std::cerr << "JSON root must be an array.\n";
            return 1;
        }

        int printed = 0;

        for (const auto& entry : data) {
            std::string name = entry.value("name", "");
            std::string githubUsername = entry.value("githubUsername", "");
            int year = entry.value("year", 0);

            if (name == "Your Name" || githubUsername == "your-github-username" || year == 0) {
                continue;
            }

            std::cout << "Name: " << name << "\n";
            std::cout << "GitHub Username: " << githubUsername << "\n";
            std::cout << "Year: " << year << "\n";
            std::cout << "Major: " << entry.value("major", "") << "\n";
            std::cout << "Favorite Hobby: " << entry.value("favoriteHobby", "") << "\n\n";
            ++printed;
        }

        if (printed == 0) {
            std::cout << "No non-example entries found.\n";
        }
    } catch (const std::exception& e) {
        std::cerr << "JSON parse error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
